# Generated by Django 4.1 on 2023-06-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='descriptin',
            new_name='description',
        ),
    ]
