# Generated by Django 4.1 on 2023-07-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_orderdata_delete_orderdta'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='total',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
